#include "..\NES.h"

CpuOpcodeStruct gCpuOpcodeList[] =
{
	{ 0x00, INSTRUCTION_TYPE_BRK, ADDRESS_MODE_INTERRUPT },
	{ 0x01, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_INDIRECT_X },
	{ 0x02, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x03, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_INDIRECT_X },
	{ 0x04, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE },
	{ 0x05, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_ZERO_PAGE },
	{ 0x06, INSTRUCTION_TYPE_ASL, ADDRESS_MODE_ZERO_PAGE },
	{ 0x07, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_ZERO_PAGE },
	{ 0x08, INSTRUCTION_TYPE_PHP, ADDRESS_MODE_PUSH },
	{ 0x09, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_IMMEDIATE },
	{ 0x0A, INSTRUCTION_TYPE_ASL, ADDRESS_MODE_ACCUMULATOR },
	{ 0x0C, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE },
	{ 0x0D, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_ABSOLUTE },
	{ 0x0E, INSTRUCTION_TYPE_ASL, ADDRESS_MODE_ABSOLUTE },
	{ 0x0F, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_ABSOLUTE },
	{ 0x10, INSTRUCTION_TYPE_BPL, ADDRESS_MODE_RELATIVE },
	{ 0x11, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_INDIRECT_Y },
	{ 0x12, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x13, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_INDIRECT_Y },
	{ 0x14, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x15, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x16, INSTRUCTION_TYPE_ASL, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x17, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x18, INSTRUCTION_TYPE_CLC, ADDRESS_MODE_IMPLIED },
	{ 0x19, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x1A, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0x1B, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x1C, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x1D, INSTRUCTION_TYPE_ORA, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x1E, INSTRUCTION_TYPE_ASL, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x1F, INSTRUCTION_TYPE_SLO, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x20, INSTRUCTION_TYPE_JSR, ADDRESS_MODE_SPECIAL },
	{ 0x21, INSTRUCTION_TYPE_AND, ADDRESS_MODE_INDIRECT_X },
	{ 0x22, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x23, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_INDIRECT_X },
	{ 0x24, INSTRUCTION_TYPE_BIT, ADDRESS_MODE_ZERO_PAGE },
	{ 0x25, INSTRUCTION_TYPE_AND, ADDRESS_MODE_ZERO_PAGE },
	{ 0x26, INSTRUCTION_TYPE_ROL, ADDRESS_MODE_ZERO_PAGE },
	{ 0x27, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_ZERO_PAGE },
	{ 0x28, INSTRUCTION_TYPE_PLP, ADDRESS_MODE_POP },
	{ 0x29, INSTRUCTION_TYPE_AND, ADDRESS_MODE_IMMEDIATE },
	{ 0x2A, INSTRUCTION_TYPE_ROL, ADDRESS_MODE_ACCUMULATOR },
	{ 0x2C, INSTRUCTION_TYPE_BIT, ADDRESS_MODE_ABSOLUTE },
	{ 0x2D, INSTRUCTION_TYPE_AND, ADDRESS_MODE_ABSOLUTE },
	{ 0x2E, INSTRUCTION_TYPE_ROL, ADDRESS_MODE_ABSOLUTE },
	{ 0x2F, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_ABSOLUTE },
	{ 0x30, INSTRUCTION_TYPE_BMI, ADDRESS_MODE_RELATIVE },
	{ 0x31, INSTRUCTION_TYPE_AND, ADDRESS_MODE_INDIRECT_Y },
	{ 0x32, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x33, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_INDIRECT_Y },
	{ 0x34, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x35, INSTRUCTION_TYPE_AND, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x36, INSTRUCTION_TYPE_ROL, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x37, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x38, INSTRUCTION_TYPE_SEC, ADDRESS_MODE_IMPLIED },
	{ 0x39, INSTRUCTION_TYPE_AND, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x3A, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0x3B, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x3C, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x3D, INSTRUCTION_TYPE_AND, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x3E, INSTRUCTION_TYPE_ROL, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x3F, INSTRUCTION_TYPE_RLA, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x40, INSTRUCTION_TYPE_RTI, ADDRESS_MODE_SPECIAL },
	{ 0x41, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_INDIRECT_X },
	{ 0x42, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x43, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_INDIRECT_X },
	{ 0x44, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE },
	{ 0x45, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_ZERO_PAGE },
	{ 0x46, INSTRUCTION_TYPE_LSR, ADDRESS_MODE_ZERO_PAGE },
	{ 0x47, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_ZERO_PAGE },
	{ 0x48, INSTRUCTION_TYPE_PHA, ADDRESS_MODE_PUSH },
	{ 0x49, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_IMMEDIATE },
	{ 0x4A, INSTRUCTION_TYPE_LSR, ADDRESS_MODE_ACCUMULATOR },
	{ 0x4C, INSTRUCTION_TYPE_JMP, ADDRESS_MODE_ABSOLUTE },
	{ 0x4D, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_ABSOLUTE },
	{ 0x4E, INSTRUCTION_TYPE_LSR, ADDRESS_MODE_ABSOLUTE },
	{ 0x4F, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_ABSOLUTE },
	{ 0x50, INSTRUCTION_TYPE_BVC, ADDRESS_MODE_RELATIVE },
	{ 0x51, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_INDIRECT_Y },
	{ 0x52, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x53, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_INDIRECT_Y },
	{ 0x54, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x55, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x56, INSTRUCTION_TYPE_LSR, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x57, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x58, INSTRUCTION_TYPE_CLI, ADDRESS_MODE_IMPLIED },
	{ 0x59, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x5A, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0x5B, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x5C, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x5D, INSTRUCTION_TYPE_EOR, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x5E, INSTRUCTION_TYPE_LSR, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x5F, INSTRUCTION_TYPE_SRE, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x60, INSTRUCTION_TYPE_RTS, ADDRESS_MODE_SPECIAL },
	{ 0x61, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_INDIRECT_X },
	{ 0x62, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x63, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_INDIRECT_X },
	{ 0x64, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE },
	{ 0x65, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_ZERO_PAGE },
	{ 0x66, INSTRUCTION_TYPE_ROR, ADDRESS_MODE_ZERO_PAGE },
	{ 0x67, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_ZERO_PAGE },
	{ 0x68, INSTRUCTION_TYPE_PLA, ADDRESS_MODE_POP },
	{ 0x69, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_IMMEDIATE },
	{ 0x6A, INSTRUCTION_TYPE_ROR, ADDRESS_MODE_ACCUMULATOR },
	{ 0x6C, INSTRUCTION_TYPE_JMP, ADDRESS_MODE_INDIRECT },
	{ 0x6D, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_ABSOLUTE },
	{ 0x6E, INSTRUCTION_TYPE_ROR, ADDRESS_MODE_ABSOLUTE },
	{ 0x6F, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_ABSOLUTE },
	{ 0x70, INSTRUCTION_TYPE_BVS, ADDRESS_MODE_RELATIVE },
	{ 0x71, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_INDIRECT_Y },
	{ 0x72, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x73, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_INDIRECT_Y },
	{ 0x74, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x75, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x76, INSTRUCTION_TYPE_ROR, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x77, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x78, INSTRUCTION_TYPE_SEI, ADDRESS_MODE_IMPLIED },
	{ 0x79, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x7A, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0x7B, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x7C, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x7D, INSTRUCTION_TYPE_ADC, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x7E, INSTRUCTION_TYPE_ROR, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x7F, INSTRUCTION_TYPE_RRA, ADDRESS_MODE_ABSOLUTE_X },
	{ 0x80, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMMEDIATE },
	{ 0x81, INSTRUCTION_TYPE_STA, ADDRESS_MODE_INDIRECT_X },
	{ 0x82, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMMEDIATE },
	{ 0x83, INSTRUCTION_TYPE_SAX, ADDRESS_MODE_INDIRECT_X },
	{ 0x84, INSTRUCTION_TYPE_STY, ADDRESS_MODE_ZERO_PAGE },
	{ 0x85, INSTRUCTION_TYPE_STA, ADDRESS_MODE_ZERO_PAGE },
	{ 0x86, INSTRUCTION_TYPE_STX, ADDRESS_MODE_ZERO_PAGE },
	{ 0x87, INSTRUCTION_TYPE_SAX, ADDRESS_MODE_ZERO_PAGE },
	{ 0x88, INSTRUCTION_TYPE_DEY, ADDRESS_MODE_IMPLIED },
	{ 0x89, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMMEDIATE },
	{ 0x8A, INSTRUCTION_TYPE_TXA, ADDRESS_MODE_IMPLIED },
	{ 0x8C, INSTRUCTION_TYPE_STY, ADDRESS_MODE_ABSOLUTE },
	{ 0x8D, INSTRUCTION_TYPE_STA, ADDRESS_MODE_ABSOLUTE },
	{ 0x8E, INSTRUCTION_TYPE_STX, ADDRESS_MODE_ABSOLUTE },
	{ 0x8F, INSTRUCTION_TYPE_SAX, ADDRESS_MODE_ABSOLUTE },
	{ 0x90, INSTRUCTION_TYPE_BCC, ADDRESS_MODE_RELATIVE },
	{ 0x91, INSTRUCTION_TYPE_STA, ADDRESS_MODE_INDIRECT_Y },
	{ 0x92, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0x94, INSTRUCTION_TYPE_STY, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x95, INSTRUCTION_TYPE_STA, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0x96, INSTRUCTION_TYPE_STX, ADDRESS_MODE_ZERO_PAGE_Y },
	{ 0x97, INSTRUCTION_TYPE_SAX, ADDRESS_MODE_ZERO_PAGE_Y },
	{ 0x98, INSTRUCTION_TYPE_TYA, ADDRESS_MODE_IMPLIED },
	{ 0x99, INSTRUCTION_TYPE_STA, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0x9A, INSTRUCTION_TYPE_TXS, ADDRESS_MODE_IMPLIED },
	{ 0x9D, INSTRUCTION_TYPE_STA, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xA0, INSTRUCTION_TYPE_LDY, ADDRESS_MODE_IMMEDIATE },
	{ 0xA1, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_INDIRECT_X },
	{ 0xA2, INSTRUCTION_TYPE_LDX, ADDRESS_MODE_IMMEDIATE },
	{ 0xA3, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_INDIRECT_X },
	{ 0xA4, INSTRUCTION_TYPE_LDY, ADDRESS_MODE_ZERO_PAGE },
	{ 0xA5, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_ZERO_PAGE },
	{ 0xA6, INSTRUCTION_TYPE_LDX, ADDRESS_MODE_ZERO_PAGE },
	{ 0xA7, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_ZERO_PAGE },
	{ 0xA8, INSTRUCTION_TYPE_TAY, ADDRESS_MODE_IMPLIED },
	{ 0xA9, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_IMMEDIATE },
	{ 0xAA, INSTRUCTION_TYPE_TAX, ADDRESS_MODE_IMPLIED },
	{ 0xAC, INSTRUCTION_TYPE_LDY, ADDRESS_MODE_ABSOLUTE },
	{ 0xAD, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_ABSOLUTE },
	{ 0xAE, INSTRUCTION_TYPE_LDX, ADDRESS_MODE_ABSOLUTE },
	{ 0xAF, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_ABSOLUTE },
	{ 0xB0, INSTRUCTION_TYPE_BCS, ADDRESS_MODE_RELATIVE },
	{ 0xB1, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_INDIRECT_Y },
	{ 0xB2, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0xB3, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_INDIRECT_Y },
	{ 0xB4, INSTRUCTION_TYPE_LDY, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xB5, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xB6, INSTRUCTION_TYPE_LDX, ADDRESS_MODE_ZERO_PAGE_Y },
	{ 0xB7, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_ZERO_PAGE_Y },
	{ 0xB8, INSTRUCTION_TYPE_CLV, ADDRESS_MODE_IMPLIED },
	{ 0xB9, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xBA, INSTRUCTION_TYPE_TSX, ADDRESS_MODE_IMPLIED },
	{ 0xBC, INSTRUCTION_TYPE_LDY, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xBD, INSTRUCTION_TYPE_LDA, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xBE, INSTRUCTION_TYPE_LDX, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xBF, INSTRUCTION_TYPE_LAX, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xC0, INSTRUCTION_TYPE_CPY, ADDRESS_MODE_IMMEDIATE },
	{ 0xC1, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_INDIRECT_X },
	{ 0xC2, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMMEDIATE },
	{ 0xC3, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_INDIRECT_X },
	{ 0xC4, INSTRUCTION_TYPE_CPY, ADDRESS_MODE_ZERO_PAGE },
	{ 0xC5, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_ZERO_PAGE },
	{ 0xC6, INSTRUCTION_TYPE_DEC, ADDRESS_MODE_ZERO_PAGE },
	{ 0xC7, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_ZERO_PAGE },
	{ 0xC8, INSTRUCTION_TYPE_INY, ADDRESS_MODE_IMPLIED },
	{ 0xC9, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_IMMEDIATE },
	{ 0xCA, INSTRUCTION_TYPE_DEX, ADDRESS_MODE_IMPLIED },
	{ 0xCC, INSTRUCTION_TYPE_CPY, ADDRESS_MODE_ABSOLUTE },
	{ 0xCD, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_ABSOLUTE },
	{ 0xCE, INSTRUCTION_TYPE_DEC, ADDRESS_MODE_ABSOLUTE },
	{ 0xCF, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_ABSOLUTE },
	{ 0xD0, INSTRUCTION_TYPE_BNE, ADDRESS_MODE_RELATIVE },
	{ 0xD1, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_INDIRECT_Y },
	{ 0xD2, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0xD3, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_INDIRECT_Y },
	{ 0xD4, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xD5, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xD6, INSTRUCTION_TYPE_DEC, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xD7, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xD8, INSTRUCTION_TYPE_CLD, ADDRESS_MODE_IMPLIED },
	{ 0xD9, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xDA, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0xDB, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xDC, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xDD, INSTRUCTION_TYPE_CMP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xDE, INSTRUCTION_TYPE_DEC, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xDF, INSTRUCTION_TYPE_DCP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xE0, INSTRUCTION_TYPE_CPX, ADDRESS_MODE_IMMEDIATE },
	{ 0xE1, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_INDIRECT_X },
	{ 0xE2, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMMEDIATE },
	{ 0xE3, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_INDIRECT_X },
	{ 0xE4, INSTRUCTION_TYPE_CPX, ADDRESS_MODE_ZERO_PAGE },
	{ 0xE5, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_ZERO_PAGE },
	{ 0xE6, INSTRUCTION_TYPE_INC, ADDRESS_MODE_ZERO_PAGE },
	{ 0xE7, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_ZERO_PAGE },
	{ 0xE8, INSTRUCTION_TYPE_INX, ADDRESS_MODE_IMPLIED },
	{ 0xE9, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_IMMEDIATE },
	{ 0xEA, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0xEB, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_IMMEDIATE },
	{ 0xEC, INSTRUCTION_TYPE_CPX, ADDRESS_MODE_ABSOLUTE },
	{ 0xED, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_ABSOLUTE },
	{ 0xEE, INSTRUCTION_TYPE_INC, ADDRESS_MODE_ABSOLUTE },
	{ 0xEF, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_ABSOLUTE },
	{ 0xF0, INSTRUCTION_TYPE_BEQ, ADDRESS_MODE_RELATIVE },
	{ 0xF1, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_INDIRECT_Y },
	{ 0xF2, INSTRUCTION_TYPE_STP, ADDRESS_MODE_SPECIAL },
	{ 0xF3, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_INDIRECT_Y },
	{ 0xF4, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xF5, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xF6, INSTRUCTION_TYPE_INC, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xF7, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_ZERO_PAGE_X },
	{ 0xF8, INSTRUCTION_TYPE_SED, ADDRESS_MODE_IMPLIED },
	{ 0xF9, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xFA, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_IMPLIED },
	{ 0xFB, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_ABSOLUTE_Y },
	{ 0xFC, INSTRUCTION_TYPE_NOP, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xFD, INSTRUCTION_TYPE_SBC, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xFE, INSTRUCTION_TYPE_INC, ADDRESS_MODE_ABSOLUTE_X },
	{ 0xFF, INSTRUCTION_TYPE_ISC, ADDRESS_MODE_ABSOLUTE_X },
};

CpuInstructionAttributesStruct gCpuInstructionAttributesList[] =
{
	{ INSTRUCTION_TYPE_ADC, "ADC", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_ADC },
	{ INSTRUCTION_TYPE_AND, "AND", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_AND },
	{ INSTRUCTION_TYPE_ASL, "ASL", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_ASL },
	{ INSTRUCTION_TYPE_BCC, "BCC", 0, NULL },
	{ INSTRUCTION_TYPE_BCS, "BCS", 0, NULL },
	{ INSTRUCTION_TYPE_BEQ, "BEQ", 0, NULL },
	{ INSTRUCTION_TYPE_BIT, "BIT", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_BIT },
	{ INSTRUCTION_TYPE_BMI, "BMI", 0, NULL },
	{ INSTRUCTION_TYPE_BNE, "BNE", 0, NULL },
	{ INSTRUCTION_TYPE_BPL, "BPL", 0, NULL },
	{ INSTRUCTION_TYPE_BRK, "BRK", 0, NULL },
	{ INSTRUCTION_TYPE_BVC, "BVC", 0, NULL },
	{ INSTRUCTION_TYPE_BVS, "BVS", 0, NULL },
	{ INSTRUCTION_TYPE_CLC, "CLC", 0, NULL },
	{ INSTRUCTION_TYPE_CLD, "CLD", 0, NULL },
	{ INSTRUCTION_TYPE_CLI, "CLI", 0, NULL },
	{ INSTRUCTION_TYPE_CLV, "CLV", 0, NULL },
	{ INSTRUCTION_TYPE_CMP, "CMP", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_CMP },
	{ INSTRUCTION_TYPE_CPX, "CPX", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_CPX },
	{ INSTRUCTION_TYPE_CPY, "CPY", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_CPY },
	{ INSTRUCTION_TYPE_DCP, "DCP", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_DCP },
	{ INSTRUCTION_TYPE_DEC, "DEC", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_DEC },
	{ INSTRUCTION_TYPE_DEX, "DEX", 0, NULL },
	{ INSTRUCTION_TYPE_DEY, "DEY", 0, NULL },
	{ INSTRUCTION_TYPE_EOR, "EOR", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_EOR },
	{ INSTRUCTION_TYPE_INC, "INC", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_INC },
	{ INSTRUCTION_TYPE_INX, "INX", 0, NULL },
	{ INSTRUCTION_TYPE_INY, "INY", 0, NULL },
	{ INSTRUCTION_TYPE_ISC, "ISC", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_ISC },
	{ INSTRUCTION_TYPE_JMP, "JMP", 0, NULL },
	{ INSTRUCTION_TYPE_JSR, "JSR", 0, NULL },
	{ INSTRUCTION_TYPE_LAX, "LAX", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_LAX },
	{ INSTRUCTION_TYPE_LDA, "LDA", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_LDA },
	{ INSTRUCTION_TYPE_LDX, "LDX", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_LDX },
	{ INSTRUCTION_TYPE_LDY, "LDY", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_LDY },
	{ INSTRUCTION_TYPE_LSR, "LSR", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_LSR },
	{ INSTRUCTION_TYPE_NOP, "NOP", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_NOP },
	{ INSTRUCTION_TYPE_ORA, "ORA", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_ORA },
	{ INSTRUCTION_TYPE_PHA, "PHA", 0, NULL },
	{ INSTRUCTION_TYPE_PHP, "PHP", 0, NULL },
	{ INSTRUCTION_TYPE_PLA, "PLA", 0, NULL },
	{ INSTRUCTION_TYPE_PLP, "PLP", 0, NULL },
	{ INSTRUCTION_TYPE_RLA, "RLA", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_RLA },
	{ INSTRUCTION_TYPE_ROL, "ROL", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_ROL },
	{ INSTRUCTION_TYPE_ROR, "ROR", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_ROR },
	{ INSTRUCTION_TYPE_RRA, "RRA", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_RRA },
	{ INSTRUCTION_TYPE_RTI, "RTI", 0, NULL },
	{ INSTRUCTION_TYPE_RTS, "RTS", 0, NULL },
	{ INSTRUCTION_TYPE_SAX, "SAX", INSTRUCTION_FLAGS_WRITE, CommonInstructionHandler_SAX },
	{ INSTRUCTION_TYPE_SBC, "SBC", INSTRUCTION_FLAGS_READ, CommonInstructionHandler_SBC },
	{ INSTRUCTION_TYPE_SEC, "SEC", 0, NULL },
	{ INSTRUCTION_TYPE_SED, "SED", 0, NULL },
	{ INSTRUCTION_TYPE_SEI, "SEI", 0, NULL },
	{ INSTRUCTION_TYPE_SLO, "SLO", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_SLO },
	{ INSTRUCTION_TYPE_SRE, "SRE", INSTRUCTION_FLAGS_READ_MODIFY_WRITE, CommonInstructionHandler_SRE },
	{ INSTRUCTION_TYPE_STA, "STA", INSTRUCTION_FLAGS_WRITE, CommonInstructionHandler_STA },
	{ INSTRUCTION_TYPE_STP, "STP", 0, NULL },
	{ INSTRUCTION_TYPE_STX, "STX", INSTRUCTION_FLAGS_WRITE, CommonInstructionHandler_STX },
	{ INSTRUCTION_TYPE_STY, "STY", INSTRUCTION_FLAGS_WRITE, CommonInstructionHandler_STY },
	{ INSTRUCTION_TYPE_TAX, "TAX", 0, NULL },
	{ INSTRUCTION_TYPE_TAY, "TAY", 0, NULL },
	{ INSTRUCTION_TYPE_TSX, "TSX", 0, NULL },
	{ INSTRUCTION_TYPE_TXA, "TXA", 0, NULL },
	{ INSTRUCTION_TYPE_TXS, "TXS", 0, NULL },
	{ INSTRUCTION_TYPE_TYA, "TYA", 0, NULL },
};

CpuOpcodeStruct gCpuOpcodePlaceholderList[] = 
{
	{ 0x00, INSTRUCTION_TYPE_NMI, ADDRESS_MODE_INTERRUPT },
	{ 0x00, INSTRUCTION_TYPE_DMA, ADDRESS_MODE_DMA },
};

CpuInstructionAttributesStruct gCpuInstructionAttributesPlaceholderList[] =
{
	{ INSTRUCTION_TYPE_NMI, "NMI", 0, NULL },
	{ INSTRUCTION_TYPE_DMA, "DMA", 0, NULL },
};

OpcodeLookupTableEntryStruct gOpcodeLookupTable[256];

DWORD PopulateOpcodeLookupTable()
{
	CpuOpcodeStruct *pCpuOpcode = NULL;
	CpuInstructionAttributesStruct *pCpuInstructionAttributes = NULL;

	// populate fast opcode lookup table
	for(DWORD i = 0; i < 256; i++)
	{
		// find instruction by opcode
		for(DWORD ii = 0; ii < ELEMENT_COUNT(gCpuOpcodeList); ii++)
		{
			if(gCpuOpcodeList[ii].bOpcode == i)
			{
				pCpuOpcode = &gCpuOpcodeList[ii];
				break;
			}
		}
		if(pCpuOpcode != NULL)
		{
			// find instruction attribute data
			for(DWORD ii = 0; ii < ELEMENT_COUNT(gCpuInstructionAttributesList); ii++)
			{
				if(gCpuInstructionAttributesList[ii].InstructionType == pCpuOpcode->InstructionType)
				{
					pCpuInstructionAttributes = &gCpuInstructionAttributesList[ii];
					break;
				}
			}
			if(pCpuInstructionAttributes == NULL)
			{
				// attribute data not found for this instruction type - error
				return 1;
			}
		}

		// store pointers in lookup table
		gOpcodeLookupTable[i].pCpuOpcode = pCpuOpcode;
		gOpcodeLookupTable[i].pCpuInstructionAttributes = pCpuInstructionAttributes;
	}

	return 0;
}

DWORD LookupInstruction(BYTE bOpcode, CpuOpcodeStruct **ppCpuOpcode, CpuInstructionAttributesStruct **ppCpuInstructionAttributes)
{
	OpcodeLookupTableEntryStruct *pOpcodeLookupTableEntry = NULL;

	pOpcodeLookupTableEntry = &gOpcodeLookupTable[bOpcode];
	if(pOpcodeLookupTableEntry->pCpuOpcode == NULL)
	{
		// invalid opcode
		return 1;
	}

	// store pointers
	*ppCpuOpcode = pOpcodeLookupTableEntry->pCpuOpcode;
	*ppCpuInstructionAttributes = pOpcodeLookupTableEntry->pCpuInstructionAttributes;

	return 0;
}

DWORD LookupInstruction_Placeholder(InstructionTypeEnum InstructionType, CpuOpcodeStruct **ppCpuOpcode, CpuInstructionAttributesStruct **ppCpuInstructionAttributes)
{
	CpuOpcodeStruct *pCpuOpcode = NULL;
	CpuInstructionAttributesStruct *pCpuInstructionAttributes = NULL;

	// find placeholder instruction
	for(DWORD i = 0; i < ELEMENT_COUNT(gCpuOpcodePlaceholderList); i++)
	{
		if(gCpuOpcodePlaceholderList[i].InstructionType == InstructionType)
		{
			pCpuOpcode = &gCpuOpcodePlaceholderList[i];
			break;
		}
	}
	if(pCpuOpcode == NULL)
	{
		// not found
		return 1;
	}

	// find placeholder instruction attribute data
	for(DWORD i = 0; i < ELEMENT_COUNT(gCpuInstructionAttributesPlaceholderList); i++)
	{
		if(gCpuInstructionAttributesPlaceholderList[i].InstructionType == pCpuOpcode->InstructionType)
		{
			pCpuInstructionAttributes = &gCpuInstructionAttributesPlaceholderList[i];
			break;
		}
	}
	if(pCpuInstructionAttributes == NULL)
	{
		// not found
		return 1;
	}

	// store pointers
	*ppCpuOpcode = pCpuOpcode;
	*ppCpuInstructionAttributes = pCpuInstructionAttributes;

	return 0;
}
